# Generated by Django 5.1.2 on 2024-10-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desert',
            name='name',
            field=models.CharField(default='Название не указано', max_length=255, verbose_name='Название'),
        ),
    ]
