# Generated by Django 5.1.2 on 2024-10-29 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0002_desert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='desert',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поступления'),
        ),
    ]
