# Generated by Django 5.1.2 on 2024-10-30 04:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0004_remove_desert_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название булочки')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поступления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Булочка',
                'verbose_name_plural': 'Булочки',
            },
        ),
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название пирога')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поступления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Пирог',
                'verbose_name_plural': 'Пироги',
            },
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название печенья')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поступления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Печенье',
                'verbose_name_plural': 'Печеньи',
            },
        ),
        migrations.CreateModel(
            name='Cupcakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название капкейка')),
                ('price', models.CharField(max_length=80, verbose_name='Цена')),
                ('added_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время поступления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.category', verbose_name='Выберите категорию')),
            ],
            options={
                'verbose_name': 'Капкейк',
                'verbose_name_plural': 'Капкейки',
            },
        ),
    ]
