# Generated by Django 5.1.2 on 2024-10-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='products/imgs/', verbose_name='Изображение'),
        ),
    ]
