# Generated by Django 5.1.2 on 2024-10-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0008_category_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bun',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conf_app.product')),
            ],
            options={
                'verbose_name': 'Булочка',
                'verbose_name_plural': 'Булочки',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conf_app.product')),
            ],
            options={
                'verbose_name': 'Торт',
                'verbose_name_plural': 'Торты',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conf_app.product')),
            ],
            options={
                'verbose_name': 'Печенье',
                'verbose_name_plural': 'Печенья',
            },
        ),
        migrations.CreateModel(
            name='Cupcake',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='conf_app.product')),
            ],
            options={
                'verbose_name': 'Капкейк',
                'verbose_name_plural': 'Капкейки',
            },
        ),
        migrations.RemoveField(
            model_name='cakes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cookies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cupcakes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='desert',
            name='category',
        ),
        migrations.DeleteModel(
            name='Buns',
        ),
        migrations.DeleteModel(
            name='Cakes',
        ),
        migrations.DeleteModel(
            name='Cookies',
        ),
        migrations.DeleteModel(
            name='Cupcakes',
        ),
        migrations.DeleteModel(
            name='Desert',
        ),
    ]
