# Generated by Django 5.1.2 on 2024-10-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0009_bun_cake_cookie_cupcake_remove_cakes_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Пироги', 'verbose_name_plural': 'Пироги'},
        ),
    ]
