# Generated by Django 5.1.2 on 2024-10-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0012_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=80, verbose_name='Цена'),
        ),
    ]
