# Generated by Django 5.1.2 on 2024-11-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0014_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('entrance', models.CharField(max_length=100)),
                ('apartament', models.CharField(max_length=20)),
                ('comm_for_order', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адресы',
            },
        ),
    ]
