# Generated by Django 5.1.2 on 2024-11-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0015_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='apartament',
            field=models.CharField(max_length=20, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='comm_for_order',
            field=models.CharField(max_length=255, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='entrance',
            field=models.CharField(max_length=100, verbose_name='Подъезд'),
        ),
    ]
