# Generated by Django 5.1.2 on 2024-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0019_remove_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cart_items',
            field=models.ManyToManyField(related_name='deliveries', to='conf_app.cartitem', verbose_name='Позиции корзины'),
        ),
    ]
